spring:
  cloud:
    stream:
      binders:
        boss:
          type: rabbit
      bindings:
        input:
          destination: queue.order.greeting
  rabbitmq:
    username: janwee
    password: janwee
    addresses: 192.168.136.133:5672