spring:
  jpa:
    database: postgresql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
    show-sql: true
    generate-ddl: false
  datasource:
    driver-class-name: org.postgresql.Driver
    username: janwee
    password: janwee
    jdbc-url: jdbc:postgresql://192.168.29.130:5432/janwee?currentSchema=book