spring:
  cloud:
    stream:
      binders:
        boss:
          type: rabbit
      bindings:
        input:
          destination: queue.book.greeting
        output:
          destination: queue.order.greeting
        textSupplier-out-0:
          destination: queue.order.text-supplier
  rabbitmq:
    username: janwee
    password: janwee
    addresses: 192.168.136.133:5672